#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64"  ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..

if [ ! -e bin/rancher-host-local-ipam ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin/
tar cvzf ../dist/artifacts/rancher-host-local-ipam-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-host-local-ipam-${ARCH}-${VERSION}.tar.gz"
